- type: entity
  name: stun baton
  parent: BaseItem
  id: Stunbaton
  components:
    - type: Sprite
      sprite: Objects/Weapons/Melee/stunbaton.rsi
      state: stunbaton_off

    - type: Icon
      sprite: Objects/Weapons/Melee/stunbaton.rsi
      state: stunbaton_off

    - type: Stunbaton
      damage: 1
      range: 0.75
      arcwidth: 0
      arc: default

    - type: Item
      Size: 10
      sprite: Objects/Weapons/Melee/stunbaton.rsi
      HeldPrefix: off

    - type: ItemCooldown
