- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 #4 hrs
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesClown
    mask: ClothingMaskClownUnremoveable
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    # the purple glasses?
  innerClothingSkirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
