# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: "chief medical officer"
  requirements:
    - job: MedicalDoctor
      time: 14400 # 4 hours
  weight: 10
  startingGear: CMOGear
  departments:
  - Command
  - Medical
  icon: "ChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    id: CMOPDA
    ears: ClothingHeadsetAltMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
