- type: job
  id: Coroner
  name: job-name-coroner
  description: job-description-coroner
  playTimeTracker: JobCoroner
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0
  startingGear: CoronerGear
  icon: "Coroner"
  supervisors: job-supervisors-medicine
  canBeAntag: true
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: CoronerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackMedicalFilled
    pocket1: Paper
    shoes: ClothingShoesColorBlack
    id: CoronerPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled