- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1800
  startingGear: ParamedicGear
  icon: "Paramedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  - External
  - Service
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatParamedicWB
    head: ClothingHeadHatParamedicsoft
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    pocket1: HandheldCrewMonitor
    belt: ClothingBeltParamedicFilled
  innerclothingskirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
