- type: department
  id: Logistics
  description: department-mystic-Logistics-description
  color: "#A46106"
  roles:
  - LogisticsSpecialist
  - Quartermaster

- type: department
  id: Civilian
  description: department-mystic-Service-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - ServiceLeader
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  description: department-mystic-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - ChiefSecurityOfficer
  - Director
  - MasterArcanist
  - ServiceLeader
  - Quartermaster
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: department-mystic-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-mystic-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  description: department-mystic-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - ChiefSecurityOfficer
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden

- type: department
  id: Arcaneology
  description: department-mystic-Arcaneology-description
  color: "#D381C9"
  roles:
  - MasterArcanist
  - MysticFledgling
  - MysticResearcher
  - OtherspaceExplorer

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false
