"Changes: Sprites":
- '**/*.rsi/*.png'

"Changes: Map":
- 'Resources/Maps/*.yml'
- 'Resources/Maps/*.yaml'
- 'Resources/Prototypes/Maps/*.yml'
- 'Resources/Prototypes/Maps/*.yaml'

"Changes: UI":
- '**/*.xaml*'

"No C#":
- all: ["!**/*.cs"]
