- type: entity
  parent: Clothing
  id: HatBase
  abstract: true
  components:
  - type: Clothing
    Slots:
    - Helmet
  - type: Sprite
    state: icon

- type: entity
  parent: HatBase
  id: HelmetHardsuitBase
  name: base hardsuit helmet
  abstract: true
  components:
    - type: PressureProtection
      highPressureMultiplier: 0.75
      lowPressureMultiplier: 100
