# The one mob to rule them all
- type: entity
  id: MobBase
  name: Base mob (YOU SHOULD NOT SEE THIS)
  abstract: true
  components:
  - type: Sprite
    netsync: false
    drawdepth: Mobs
    noRot: true
  - type: Physics
    bodyType: KinematicController
  - type: Strippable
  - type: UserInterface
    interfaces:
    - key: enum.StrippingUiKey.Key
      type: StrippableBoundUserInterface
  - type: MovementSpeedModifier
  - type: Clickable
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: DoAfter
  - type: Pullable
  
- type: entity
  parent: MobBase
  id: MobOrganicBase
  save: false
  name: Urist McHands
  description: A miserable pile of secrets.
  abstract: true
  components:
  - type: Flashable
  - type: Sprite
    netsync: false
  - type: Tag
    tags:
    - CanPilot
    - FootstepSound
    - DoorBumpOpener
  - type: Reactive
    groups:
      Flammable: [ Touch ]
      Extinguish: [ Touch ]
      Acidic: [Touch, Ingestion]
    reactions:
    - reagents: [Water, SpaceCleaner]
      methods: [Touch]
      effects:
      - !type:WashCreamPieReaction
  - type: Hands
  - type: MovedByPressure
  - type: Barotrauma
    damage:
      types:
        Blunt: 0.7 #per second, scales with pressure and other constants.
  - type: Hunger
    damage:
      types:
        Blunt: 2
  - type: Thirst
    damage:
      types:
        Blunt: 2
  # Organs
  - type: InjectableSolution
    solution: chemicals
  - type: DrawableSolution
    solution: bloodstream
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
  - type: Bloodstream
    bloodlossDamage:
      types:
        Bloodloss:
          1
    bloodlossHealDamage:
      types:
        Bloodloss:
          -0.25
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - Electrocution
  # Other
  - type: Inventory
  - type: InteractionOutline
  - type: Icon
    sprite: Mobs/Species/Human/parts.rsi
    state: full
  # If you update this then consider if Teshari need updating!
  - type: Fixtures
    fixtures: # TODO: This needs a second fixture just for mob collisions.
    - shape:
        !type:PhysShapeCircle
        radius: 0.35
      mass: 70
      restitution: 0.0
      mask:
      - Impassable
      - MobImpassable
      - VaultImpassable
      - SmallImpassable
      layer:
      - Opaque
  - type: AtmosExposed
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage:
      types:
        Heat: 1 #per second, scales with number of fire 'stacks'
  - type: Temperature
    heatDamageThreshold: 360
    coldDamageThreshold: 260
    currentTemperature: 310.15
    specificHeat: 42
    coldDamage:
      types:
        Cold : 1 #per second, scales with temperature & other constants
    heatDamage:
      types:
        Heat : 1 #per second, scales with temperature & other constants
  - type: HumanoidAppearance
  - type: Body
    template: HumanoidTemplate
    preset: HumanPreset
  - type: Damageable
    damageContainer: Biological
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 25
  - type: Internals
  - type: MobState
    thresholds:
      0: !type:NormalMobState {}
      100: !type:CriticalMobState {}
      200: !type:DeadMobState {}
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibBehavior { }
  - type: SlowOnDamage
    speedModifierThresholds:
      40: 0.8
      60: 0.6
      80: 0.4
      90: 0.2
  - type: HeatResistance
  - type: Appearance
    visuals:
    - type: RotationVisualizer
    - type: BuckleVisualizer
    - type: FireVisualizer
      sprite: Mobs/Effects/onfire.rsi
      normalState: Generic_mob_burning
      alternateState: Standing
      fireStackAlternateState: 3
    - type: CreamPiedVisualizer
      state: creampie_human
    - type: DamageVisualizer
      thresholds: [20, 40, 100]
      targetLayers:
      - "enum.HumanoidVisualLayers.Chest"
      - "enum.HumanoidVisualLayers.Head"
      - "enum.HumanoidVisualLayers.LArm"
      - "enum.HumanoidVisualLayers.LLeg"
      - "enum.HumanoidVisualLayers.RArm"
      - "enum.HumanoidVisualLayers.RLeg"
      damageOverlayGroups:
        Brute:
          sprite: Mobs/Effects/brute_damage.rsi
          color: "#FF0000"
        Burn:
          sprite: Mobs/Effects/burn_damage.rsi
  - type: CombatMode
  - type: Climbing
  - type: Cuffable
  - type: CharacterInfo
  - type: AnimationPlayer
  - type: Buckle
  - type: UnarmedCombat
    hitSound:
      collection: Punch
    range: 0.8
    arcwidth: 30
    arc: fist
    damage:
      types:
        Blunt: 5
  - type: CreamPied
  - type: Stripping
  - type: Puller
  - type: Butcherable
    butcheringType: Spike # TODO human.
    spawned: FoodMeat
#  - type: Recyclable Turns out turning off recycler safeties without considering the instagib is a bad idea
#    safe: false
  - type: Speech
  - type: Vocal
  - type: Emoting
  - type: Grammar
    attributes:
      proper: true
  - type: StandingState

- type: entity
  save: false
  name: Urist McHands
  id: MobOrganicDummy
  abstract: true
  description: A dummy human meant to be used in character setup.
  components:
  - type: Hands
  - type: Inventory
  - type: ContainerContainer
  - type: Sprite
    netsync: false
    noRot: true
    drawdepth: Mobs
  - type: Physics
    bodyType: Dynamic
  - type: Fixtures
    fixtures:
    - shape:
        !type:PhysShapeAabb
          bounds: "-0.35,-0.35,0.35,0.35"
      mass: 70
      restitution: 0.0
      mask:
      - Impassable
      - MobImpassable
      - VaultImpassable
      - SmallImpassable
      layer:
      - Opaque
  - type: HumanoidAppearance
  - type: Body
    template: HumanoidTemplate
    preset: HumanPreset
  - type: Damageable
    damageContainer: Biological
  - type: MobState
    thresholds:
      0: !type:NormalMobState {}
      100: !type:CriticalMobState {}
      200: !type:DeadMobState {}
  - type: Appearance
    visuals:
    - type: RotationVisualizer

- type: entity
  id: MobSiliconBase
  save: false
  abstract: true
  components:
  - type: Reactive
    groups:
      Acidic: [Touch]
  - type: Input
    context: "human"
  - type: Damageable
    damageContainer: Inorganic
  - type: Bloodstream
    bloodReagent: Oil
    bloodlossDamage:
      types:
        Bloodloss:
          1
    bloodlossHealDamage:
      types:
        Bloodloss:
          -0.25
  - type: InteractionOutline
  - type: Fixtures
    fixtures:
    - shape:
        # Circles, cuz rotation of rectangles looks very bad
        !type:PhysShapeCircle
        radius: 0.35
      mass: 20
      mask:
      - Impassable
      - MobImpassable
      - VaultImpassable
      - SmallImpassable
      layer:
      - Opaque
  - type: MovementSpeedModifier
    baseWalkSpeed : 4
    baseSprintSpeed : 3
  - type: Hands
    showInHands: false
  - type: Body
    template: DroneTemplate
    preset: DronePreset
  - type: Examiner
  - type: Puller
  - type: Recyclable
    safe: false
  - type: StandingState
  - type: Alerts
