image: mcr.microsoft.com/dotnet/sdk:7.0

stages:          # List of stages for jobs, and their order of execution
  - build
  - publish

build-debug:       # This job runs in the build stage, which runs first.
  stage: build
  retry: 2
  script:
    - apt update && apt upgrade -y
    - apt install -y python3 libfreetype6
    - mkdir .git/hooks -p
    - python3 RUN_THIS.py
    - dotnet restore
    - dotnet build --configuration Debug --no-restore /p:WarningsAsErrors=nullable /m
    - pwsh -Command "dotnet test --no-build Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0"
    - export DOTNET_gcServer=1
    - pwsh -Command "dotnet test --no-build Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0"

build-release:
  stage: build
  retry: 2
  script:
    - apt update && apt upgrade -y
    - apt install -y python3 libfreetype6
    - mkdir .git/hooks -p
    - python3 RUN_THIS.py
    - dotnet restore
    - dotnet build --configuration Release --no-restore /p:WarningsAsErrors=nullable /m
    - pwsh -Command "dotnet test --no-build Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0"
    - export DOTNET_gcServer=1
    - pwsh -Command "dotnet test --no-build Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0"

publish:
  stage: publish
  script:
    - apt update && apt upgrade -y
    - apt install -y python3 libfreetype6
    - mkdir .git/hooks -p
    - python3 RUN_THIS.py
    - Tools/package_server_build.py -p win-x64 linux-x64 osx-x64 linux-arm64 > server_build.log
    - Tools/package_client_build.py > client_build.log
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - release/
      - server_build.log
      - client_build.log
