- type: guideEntry
  id: Service
  name: guide-entry-service
  text: "/Server Info/Guidebook/Service.xml"
  children:
    - Cook
    - Botany

- type: guideEntry
  id: Cook
  name: guide-entry-cook
  text: "/Server Info/Guidebook/Cook.xml"
