- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 7200 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 7200 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 7200 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 7200 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobResearchDirector
      time: 7200 #Imperial role timers
    - !type:OverallPlaytimeRequirement
      time: 180000 #Imperial role timers
  weight: 20
  startingGear: CaptainGear
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
