- type: job
  id: Captain
  name: "captain"
  requirements:
    # Cap should know all the departments they lord over
    # and the jobs each dept. head has
    - job: ChiefMedicalOfficer
      time: 14400 # 4 hours
    - job: HeadOfSecurity
      time: 14400
    - job: ResearchDirector
      time: 14400
    - job: ChiefEngineer
      time: 14400
    - job: HeadOfPersonnel
      time: 14400
  weight: 20
  startingGear: CaptainGear
  departments:
  - Command
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: "Nanotrasen officials"
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
