- type: job
  id: HeadOfService
  name: job-name-head-of-service
  description: job-description-head-of-service
  playTimeTracker: JobHeadOfService
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
  weight: 20
  startingGear: HosGear
  icon: "JobIconHeadOfService"
  requireAdminNotify: true
  supervisors: job-supervisors-director
  canBeAntag: false
  access:
  - Command
  - HeadOfService
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the director instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HosGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HosPDA
    gloves: ClothingHandsGlovesHead-Of-Service
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
