- type: job
  id: ServiceLeader
  name: job-name-sl
  description: job-description-sl
  playTimeTracker: JobServiceLeader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours
  weight: 20
  startingGear: SLGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-director
  canBeAntag: false
  access:
  - Command
  - ServiceLeader
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Hydroponics
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: SLGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
