- type: entity
  id: BaseMachineCircuitboard
  parent: BaseItem
  name: machine board
  abstract: true
  suffix: Machine
  components:
    - type: MachineBoard
    - type: Sprite
      sprite: Constructible/Misc/module.rsi
      state: id_mod
