- type: entity
  id: AutolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: autolathe PCB
  description: A machine printed circuit board for an autolathe
  components:
    - type: MachineBoard
      prototype: Autolathe
      requirements:
        MatterBin: 3
        Manipulator: 1
      materialRequirements:
        Glass: 1

- type: entity
  id: ProtolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: protolathe PCB
  description: A machine printed circuit board for a protolathe
  components:
    - type: MachineBoard
      prototype: Protolathe
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: CloningPodMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: cloning pod PCB
  description: A machine printed circuit board for a cloning pod
  components:
    - type: MachineBoard
      prototype: CloningPod
      requirements:
        ScanningModule: 2
        Manipulator: 2
      materialRequirements:
        Glass: 1
        Cable: 1

- type: entity
  id: MedicalScannerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: medical scanner PCB
  description: A machine printed circuit board for a medical scanner
  components:
    - type: MachineBoard
      prototype: MedicalScanner
      requirements:
        ScanningModule: 1
        Manipulator: 1
        Laser: 1
      materialRequirements:
        Glass: 1
        Cable: 1

- type: entity
  id: ChemMasterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: ChemMaster 4000 PCB
  description: A machine printed circuit board for a ChemMaster 4000
  components:
    - type: MachineBoard
      prototype: chem_master
      requirements:
        Manipulator: 1
      materialRequirements:
        Glass: 1
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: ChemDispenserMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: chem dispenser PCB
  description: A machine printed circuit board for a chem dispenser
  components:
    - type: MachineBoard
      prototype: chem_dispenser
      requirements:
        Capacitor: 1
        Manipulator: 1
        MatterBin: 2
      materialRequirements:
        Glass: 1

- type: entity
  id: HydroponicsTrayMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: hydroponics tray PCB
  description: A machine printed circuit board for a hydroponics tray
  components:
    - type: MachineBoard
      prototype: hydroponicsTray
      # See: https://github.com/vgstation-coders/vgstation13/blob/e9a806f30b4db0efa2a68b9eb42e3120d2321b6a/code/modules/hydroponics/hydro_tray.dm#L57
      requirements:
        MatterBin: 2
        ScanningModule: 1
        Capacitor: 1
      materialRequirements:
        # replacing the console screen
        Glass: 1
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: SMESMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: SMES PCB
  description: A machine printed circuit board for a SMES
  components:
    - type: Sprite
      sprite: Objects/Misc/module.rsi
      state: power_mod
    - type: MachineBoard
      prototype: BaseSmes
      requirements:
        Capacitor: 10

- type: entity
  id: SubstationMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: substation PCB
  description: A machine printed circuit board for a substation
  components:
    - type: MachineBoard
      prototype: BaseSubstation
      requirements:
        Capacitor: 3
      materialRequirements:
        CableMV: 5
        CableHV: 5

- type: entity
  id: ReagentGrinderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: reagent grinder PCB
  description: A machine printed circuit board for a reagent grinder
  components:
    - type: MachineBoard
      prototype: KitchenReagentGrinder
      requirements:
        Laser: 1
        ScanningModule: 1
        MatterBin: 2
      tagRequirements:
        GlassBeaker:
          Amount: 1
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker
