- type: job
  id: HeadOfSecurity
  name: "head of security"
  requirements:
    - !type:RoleTimeRequirement
      role: Warden
      time: 3600
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000
  weight: 10
  startingGear: HoSGear
  departments:
  - Command
  - Security
  icon: "HeadOfSecurity"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service

- type: startingGear
  id: HoSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
