- type: job
  id: HeadOfSecurity
  name: "head of security"
  head: true
  positions: 1
  startingGear: HoSGear
  department:
  - Command
  - Security
  icon: "HeadOfSecurity"
  access:
  - Command
  - HeadOfSecurity
  - Brig
  - Detective
  - Security
  - Maintenance
  - Service

- type: startingGear
  id: HoSGear
  equipment:
    innerclothing: ClothingUniformJumpsuitHoS
    backpack: ClothingBackpackSecurityFilled
    shoes: ClothingShoesJackboots
    outerclothing: OuterclothingHoSTrenchcoat
    eyes: SecGlasses
    head: HatBeretHoS
    idcard: HoSPDA
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
