- type: job
  id: SecurityOfficer
  name: "security officer"
  positions: 3
  spawnPositions: 2
  startingGear: SecurityOfficerGear
  department:
  - Security
  icon: "SecurityOfficer"
  access:
  - Security
  - Maintenance
  - Service

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    innerclothing: ClothingUniformJumpsuitSec
    backpack: SecPackFilled
    shoes: ClothingShoesJackboots
    eyes: SecGlasses
    outerclothing: OuterclothingArmorVest
    idcard: SecurityPDA
    ears: HeadsetSecurity
    belt: ClothingBeltSecurityFilled
