- type: entity
  parent: SalvageHumanCorpse
  id: ERTSecurityFilledCorpse
  suffix: Dead, Filled, ERT Security
  components:
  - type: Loadout
    prototypes: [ ERTSecurityFilledCorpseGear ]

- type: startingGear
  id: ERTSecurityFilledCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetHelmet
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterVestKevlar
    belt: ClothingBeltSecurityWebbing
    pocket1: Flare
    pocket2: Handcuffs

- type: entity
  parent: SalvageHumanCorpse
  id: ERTSecurityEmptyCorpse
  suffix: Dead, Empty, ERT Security
  components:
  - type: Loadout
    prototypes: [ ERTSecurityEmptyCorpseGear ]

- type: startingGear
  id: ERTSecurityEmptyCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    belt: ClothingBeltSecurityWebbing
    pocket1: Handcuffs

- type: entity
  parent: SalvageHumanCorpse
  id: ERTSecurityEVAFilledCorpse
  suffix: Dead, Filled, EVA, ERT Security
  components:
  - type: Loadout
    prototypes: [ ERTSecurityEVAFilledCorpseGear ]

- type: startingGear
  id: ERTSecurityEVAFilledCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterHardsuitERTSecurity
    head: ClothingHeadHelmetHardsuitERTSecurity
    suitstorage: OxygenTankFilled
    belt: ClothingBeltSecurityWebbing
    pocket1: Flare

- type: entity
  parent: SalvageHumanCorpse
  id: ERTSecurityEVAEmptyCorpse
  suffix: Dead, Empty, EVA, ERT Security
  components:
  - type: Loadout
    prototypes: [ ERTSecurityEVAEmptyCorpseGear ]

- type: startingGear
  id: ERTSecurityEVAEmptyCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    pocket1: Flare
