- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
  icon: "Borg"
  supervisors: job-supervisors-ai-laws
  canBeAntag: false
  access:
  - Maintenance
  - Service
  - External
