- type: job
  id: ChiefSecurityOfficer
  name: job-name-cso
  description: job-description-cso
  playTimeTracker: JobChiefSecurityOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # 30 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: CSOGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-director
  canBeAntag: false
  access:
  - ChiefSecurityOfficer
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CSOGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: CSOPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
