- type: dungeonConfig
  id: Experiment
  generator: !type:PrefabDunGen
    roomWhitelist:
      - SalvageExperiment
    presets:
      - Cross
  postGeneration:
    - !type:MiddleConnectionPostGen
      overlapCount: 3
      count: 3
      entities:
        - CableApcExtension
        - AirlockGlass
      edgeEntities:
        - Grille
        - Window
    - !type:MiddleConnectionPostGen
      count: 1
      entities:
        - CableApcExtension
        - AirlockGlass
    - !type:EntrancePostGen
      count: 2
      entities:
        - AirlockGlass
    - !type:InternalWindowPostGen
      entities:
        - Grille
        - Window
    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window
    # Wallmount signs
    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced
