- type: job
  id: AtmosphericTechnician
  name: "atmospheric technician"
  requirements:
    - job: StationEngineer
      time: 1800 # 30 minutes
  startingGear: AtmosphericTechnicianGear
  departments:
  - Engineering
  icon: "AtmosphericTechnician"
  supervisors: "the chief engineer"
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    head:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorWhite
    outerClothing:
    id: AtmosPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtAtmos
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
