- type: job
  id: ChiefEngineer
  name: "chief engineer"
  head: true
  positions: 1
  startingGear: ChiefEngineerGear
  department:
  - Command
  - Engineering
  icon: "ChiefEngineer"
  access:
  - Maintenance
  - Engineering
  - ChiefEngineer
  - Command
  - External

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: HatHardhatWhite
    innerclothing: ClothingUniformJumpsuitChiefEngineer
    backpack: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBrown
    idcard: CEPDA
    ears: ClothingHeadsetEngineering
    belt: ClothingBeltChiefEngineerFilled
