# Configuration preset used on Wizard's Den Leviathan

# Nothing specific yet

[game]
hostname = "[EN] Wizard's Den Leviathan [US East 1]"
soft_max_players = 80

[hub]
tags = "lang:en,region:am_n_e,rp:low"

[worldgen]
enabled = true

# classic "monstermos" "fast" spacing
[atmos]
mmos_spacing_speed = 1.0
monstermos_rip_tiles = true
space_wind = true
