# Configuration preset used on Wizard's Den Lizard

# Nothing specific yet

[game]
hostname = "[EN] Wizard's Den Lizard [US West]"
soft_max_players = 80

[looc]
crit_damage_type = "Cellular"
crit_damage_amount = 20.0

[hub]
tags = "lang:en,region:am_n_w,rp:low"
