# Configuration preset used on Wizard's Den Lizard

# Nothing specific yet

[game]
hostname = "[EN] Wizard's Den Lizard [US West]"
soft_max_players = 80

[hub]
tags = "lang:en,region:am_n_w,rp:low"

# slow "linda-only" spacing
[atmos]
monstermos_equalization = false
monstermos_depressurization = false
