- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: RiotBulletShield
  result: RiotBulletShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: RiotLaserShield
  result: RiotLaserShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: Flashbang
  result: Flashbang
  completetime: 3
  materials:
    Glass: 200
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  result: ShellShotgunBeanbag
  completetime: 2
  materials:
    Plastic: 15
    Steel: 10

- type: latheRecipe
  id: CartridgePistolRubber
  result: CartridgePistolRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  result: CartridgeMagnumRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeRifle
  result: CartridgeRifle
  completetime: 2
  materials:
    Steel: 15

- type: latheRecipe
  id: CartridgeLightRifleRubber
  result: CartridgeLightRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  result: CartridgeRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgePistol
  result: CartridgePistol
  completetime: 2
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  result: ShellShotgun
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnum
  result: CartridgeMagnum
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLightRifle
  result: CartridgeLightRifle
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: ShellShotgunFlare
  result: ShellShotgunFlare
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5

- type: latheRecipe
  id: ShellTranquilizer
  result: ShellTranquilizer
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetClown
  result: TargetClown
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: TargetSyndicate
  result: TargetSyndicate
  completetime: 5
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 500

- type: latheRecipe
  id: WeaponRifleLecter
  result: WeaponRifleLecter
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 1000

- type: latheRecipe
  id: WeaponSubMachineGunWt550
  result: WeaponSubMachineGunWt550
  completetime: 10
  materials:
    Steel: 1500
    Plastic: 500

- type: latheRecipe
  id: WeaponShotgunEnforcer
  result: WeaponShotgunEnforcer
  completetime: 10
  materials:
    Steel: 1500

- type: latheRecipe
  id: WeaponRevolverInspector
  result: WeaponRevolverInspector
  completetime: 10
  materials:
    Steel: 1000

- type: latheRecipe
  id: WeaponPistolMk58
  result: WeaponPistolMk58
  completetime: 10
  materials:
    Steel: 1000

- type: latheRecipe
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  completetime: 10
  materials:
    Steel: 1000
    Glass: 500
    Gold: 100

- type: latheRecipe
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  completetime: 10
  materials:
    Steel: 500
    Plastic: 500
    Plasma: 1000

- type: latheRecipe
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  completetime: 10
  materials:
    Steel: 200
    Glass: 1000
    Gold: 500
    Plasma: 300

- type: latheRecipe
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  completetime: 10
  materials:
    Steel: 500
    Glass: 500
    Plasma: 500
    Uranium: 500

- type: latheRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  completetime: 5
  materials:
    Steel: 650

- type: latheRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  completetime: 5
  materials:
    Steel: 1250

- type: latheRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300

- type: latheRecipe
  id: MagazineBoxRifle
  result: MagazineBoxRifle
  completetime: 5
  materials:
    Steel: 950

- type: latheRecipe
  id: MagazineBoxRifleRubber
  result: MagazineBoxRifleRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600

- type: latheRecipe
  id: MagazineBoxLightRifle
  result: MagazineBoxLightRifle
  completetime: 5
  materials:
    Steel: 1800

- type: latheRecipe
  id: MagazineBoxLightRifleRubber
  result: MagazineBoxLightRifleRubber
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600


- type: latheRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  completetime: 5
  materials:
    Steel: 200

- type: latheRecipe
  id: SpeedLoaderMagnumRubber
  result: SpeedLoaderMagnumRubber
  completetime: 5
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  id: SpeedLoaderMagnumHighVelocity
  result: SpeedLoaderMagnumHighVelocity
  completetime: 5
  materials:
    Steel: 50
    Glass: 150

- type: latheRecipe
  id: MagazineRifle
  result: MagazineRifle
  completetime: 5
  materials:
    Steel: 500

- type: latheRecipe
  id: MagazineRifleRubber
  result: MagazineRifleRubber
  completetime: 5
  materials:
    Steel: 125
    Plastic: 375

- type: latheRecipe
  id: MagazineRifleHighVelocity
  result: MagazineRifleHighVelocity
  completetime: 5
  materials:
    Steel: 125
    Glass: 375

- type: latheRecipe
  id: MagazinePistolSMGTopMounted
  result: MagazinePistolSMGTopMounted
  completetime: 5
  materials:
    Steel: 400

- type: latheRecipe
  id: MagazinePistol
  result: MagazinePistol
  completetime: 5
  materials:
    Steel: 300

- type: latheRecipe
  id: MagazinePistolRubber
  result: MagazinePistolRubber
  completetime: 5
  materials:
    Steel: 75
    Plastic: 225

- type: latheRecipe
  id: MagazinePistolRubber
  result: MagazinePistolHighVelocity
  completetime: 5
  materials:
    Steel: 75
    Glass: 225

- type: latheRecipe
  id: FoodBoxDonut
  result: FoodBoxDonut
  completetime: 5
  materials:
    Plastic: 200

- type: latheRecipe
  id: FlashlightSeclite
  result: FlashlightSeclite
  completetime: 5
  materials:
    Steel: 500

- type: latheRecipe
  id: ForensicScanner
  result: ForensicScanner
  completetime: 5
  materials:
    Steel: 500

- type: latheRecipe
  id: Disabler
  result: Disabler
  completetime: 10
  materials:
    Steel: 500
    Plastic: 500

- type: latheRecipe
  id: Bola
  result: Bola
  completetime: 3
  materials:
    Plastic: 100
    Cloth: 100

- type: latheRecipe
  id: ClothingOuterVestKevlar
  result: ClothingOuterVestKevlar
  completetime: 5
  materials:
    Steel: 500
    Cloth: 500

- type: latheRecipe
  id: ClothingOuterHelmetHelmet
  result: ClothingOuterHelmetHelmet
  completetime: 5
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ClothingOuterHelmetOld
  result: ClothingOuterHelmetOld
  completetime: 5
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ClothingOuterHelmetRiot
  result: ClothingOuterHelmetRiot
  completetime: 5
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ClothingOuterArmorRiot
  result: ClothingOuterArmorRiot
  completetime: 5
  materials:
    Steel: 600
    Plastic: 600

- type: latheRecipe
  id: ClothingOuterArmorReflective
  result: ClothingOuterArmorReflective
  completetime: 5
  materials:
    Steel: 600
    Glass: 600

- type: latheRecipe
  id: ClothingOuterArmorBulletproof
  result: ClothingOuterArmorBulletproof
  completetime: 5
  materials:
    Steel: 600
    Durathread: 600

- type: latheRecipe
  id: ClothingHandsGlovesCombat
  result: ClothingHandsGlovesCombat
  completetime: 5
  materials:
    Cloth: 300
    Durathread: 300

- type: latheRecipe
  id: ClothingOuterHardsuitSecurity
  result: ClothingOuterHardsuitSecurity
  completetime: 10
  materials:
    Steel: 1500
    Plastic: 1500

- type: latheRecipe
  id: JetpackSecurityFilled
  result: JetpackSecurityFilled
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 1000

