- type: entity
  id: BaseTabletopPiece
  parent: BaseItem
  abstract: true
  components:
  - type: TabletopDraggable
  - type: Sprite
    netsync: false
    noRot: true
  - type: Appearance
  - type: Tag
    tags:
      - TabletopPiece

- type: entity
  id: BaseBoardTabletop
  name: baseboard
  abstract: true
  noSpawn: true
  components:
  - type: Tag
    tags:
      - TabletopBoard
  - type: Sprite
    noRot: false
    drawdepth: FloorTiles
