- type: job
  id: CargoTechnician
  name: "cargo technician"
  positions: 2
  spawnPositions: 1
  startingGear: CargoTechGear
  department:
  - Cargo
  icon: "CargoTechnician"
  access:
  - Cargo
  - Maintenance

- type: startingGear
  id: CargoTechGear
  equipment:
    innerclothing: ClothingUniformJumpsuitCargoTech
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesBlack
    idcard: CargoPDA
    ears: ClothingHeadsetCargo
