- type: job
  id: Quartermaster
  name: "Quartermaster"
  positions: 1
  spawnPositions: 1
  startingGear: QuartermasterGear
  department:
  - Cargo
  icon: "QuarterMaster"
  access:
  - Cargo
  - Quartermaster
  - Maintenance

- type: startingGear
  id: QuartermasterGear
  equipment:
    innerclothing: UniformQM
    backpack: BackpackClothingFilled
    shoes: ShoesBrown
    idcard: QuartermasterPDA
    ears: HeadsetCargo
