- type: job
  id: SalvageSpecialist
  requirements:
    - job: CargoTechnician
      time: 1800 # 30 minutes
  name: "salvage specialist"
  icon: "ShaftMiner"
  startingGear: SalvageSpecialistGear
  departments:
  - Cargo
  supervisors: "the quartermaster and head of personnel"
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
