# Jumpsuit
- type: loadout
  id: ChiefOfSecurityJumpsuit
  equipment: ChiefOfSecurityJumpsuit

- type: startingGear
  id: ChiefOfSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: ChiefOfSecurityJumpskirt
  equipment: ChiefOfSecurityJumpskirt

- type: startingGear
  id: ChiefOfSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: ChiefOfSecurityTurtleneck
  equipment: ChiefOfSecurityTurtleneck

- type: startingGear
  id: ChiefOfSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: ChiefOfSecurityTurtleneckSkirt
  equipment: ChiefOfSecurityTurtleneckSkirt

- type: startingGear
  id: ChiefOfSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: ChiefOfSecurityFormalSuit
  equipment: ChiefOfSecurityFormalSuit

- type: startingGear
  id: ChiefOfSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCosformal

- type: loadout
  id: ChiefOfSecurityFormalSkirt
  equipment: ChiefOfSecurityFormalSkirt

- type: startingGear
  id: ChiefOfSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtCosformal

# Head
- type: loadout
  id: ChiefOfSecurityHead
  equipment: ChiefOfSecurityHead

- type: startingGear
  id: ChiefOfSecurityHead
  equipment:
    head: ClothingHeadHatCoshat

- type: loadout
  id: ChiefOfSecurityBeret
  equipment: ChiefOfSecurityBeret

- type: startingGear
  id: ChiefOfSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: ChiefOfSecurityCloak
  equipment: ChiefOfSecurityCloak

- type: startingGear
  id: ChiefOfSecurityCloak
  equipment:
    neck: ClothingNeckCloakCoS

- type: loadout
  id: ChiefOfSecurityMantle
  equipment: ChiefOfSecurityMantle

- type: startingGear
  id: ChiefOfSecurityMantle
  equipment:
    neck: ClothingNeckMantleCOS

# OuterClothing
- type: loadout
  id: ChiefOfSecurityCoat
  equipment: ChiefOfSecurityCoat

- type: startingGear
  id: ChiefOfSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatcosTrench

- type: loadout
  id: ChiefOfSecurityWinterCoat
  equipment: ChiefOfSecurityWinterCoat

- type: startingGear
  id: ChiefOfSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterCoS
