- type: entity
  name: "item"
  id: BaseItem
  abstract: true
  components:
  - type: Item
    size: 5
  - type: Clickable
  - type: InteractionOutline
  - type: MovedByPressure
  - type: DamageOnHighSpeedImpact
  - type: CollisionWake
  - type: TileFrictionModifier
    modifier: 0.5
  - type: Physics
    bodyType: Dynamic
    mass: 5
    fixtures:
    - shape:
        !type:PhysShapeAabb
          bounds: "-0.25,-0.25,0.25,0.25"
      layer:
      - Clickable
      mask:
      - Impassable
      - VaultImpassable
      restitution: 0.05  # We want them items B O U N C Y (They look fucking stupid)
      friction: 0.9
  - type: Sprite
    drawdepth: Items
  - type: Pullable
