- type: constructionGraph
  id: AirlockSecurity
  start: unsecuredAirlock
  graph:
  - node: unsecuredAirlock
    actions:
    - !type:SetWiresPanelSecurity
      wiresAccessible: true     
      weldingAllowed: true
    - !type:RemoveWiresPanelSecurity

## Medium security level door: a layer of steel plating protects the internal wiring
  - node: medSecurityUnfinished
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level1
      wiresAccessible: false     
      weldingAllowed: false
    edges:
    - to: unsecuredAirlock 
      completed:
      - !type:GivePrototype
        prototype: SheetSteel1
        amount: 2
      conditions:
      - !type:WirePanel {}
      steps:
      - tool: Prying
        doAfter: 4
    
    - to: medSecurity 
      conditions:  
      - !type:WirePanel {}
      steps:
      - tool: Welding
        doAfter: 3
      
  - node: medSecurity
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level2
      wiresAccessible: false     
      weldingAllowed: false
    edges:
    - to: medSecurityUnfinished 
      conditions:
      - !type:WirePanel {}
      steps:
      - tool: Welding
        doAfter: 10

## High security level door: a layer of plasteel plating protects the internal wiring
  - node: highSecurityUnfinished
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level3
      wiresAccessible: false     
      weldingAllowed: false
    edges:
    - to: unsecuredAirlock 
      completed:
      - !type:GivePrototype
        prototype: SheetPlasteel1
        amount: 2
      conditions:
      - !type:WirePanel {}
      steps:
      - tool: Prying
        doAfter: 4
    
    - to: highSecurity 
      conditions:  
      - !type:WirePanel {}
      steps:
      - tool: Welding
        doAfter: 5
      
  - node: highSecurity
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level4
      wiresAccessible: false     
      weldingAllowed: false
    edges:
    - to: highSecurityUnfinished
      conditions:
      - !type:WirePanel {}
      steps:
      - tool: Welding
        doAfter: 15
    
    - to: maxSecurity
      conditions:
      - !type:WirePanel {}
      steps:     
      - material: MetalRod
        amount: 2
        doAfter: 1

## Max security level door: an electric grill is added        
  - node: maxSecurity
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level5
      wiresAccessible: false     
      weldingAllowed: true
    edges:
    - to: highSecurity 
      completed:
      - !type:AttemptElectrocute
      - !type:GivePrototype
        prototype: PartRodMetal1
        amount: 2
      conditions:  
      - !type:WirePanel {}
      steps:
      - tool: Cutting
        doAfter: 0.5 

    - to: superMaxSecurityUnfinished
      conditions:
      - !type:WirePanel {}
      steps:     
      - material: Plasteel
        amount: 2
        doAfter: 2

## Super max security level door: an additional layer of plasteel is added     
  - node: superMaxSecurityUnfinished
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level6
      wiresAccessible: false     
      weldingAllowed: false
    edges:
    - to: maxSecurity 
      completed:
      - !type:GivePrototype
        prototype: SheetPlasteel1
        amount: 2
      conditions:
      - !type:WirePanel {}
      steps:
      - tool: Prying
        doAfter: 4
    
    - to: superMaxSecurity 
      conditions:  
      - !type:WirePanel {}
      steps:
      - tool: Welding
        doAfter: 5
      
  - node: superMaxSecurity
    actions:
    - !type:SetWiresPanelSecurity
      examine: wires-panel-component-on-examine-security-level7
      wiresAccessible: false     
      weldingAllowed: false
    edges:
    - to: superMaxSecurityUnfinished 
      conditions:
      - !type:WirePanel {}
      steps:
      - tool: Welding
        doAfter: 15
