- type: job
  id: Passenger
  name: "passenger"
  startingGear: PassengerGear
  departments:
  - Civilian
  icon: "Passenger"
  supervisors: "absolutely everyone"
  access:
  - Maintenance
  difficulty: "Easy"
  
- type: startingGear
  id: PassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
