- type: job
  id: Assistant
  name: "assistant"
  positions: -1 # Treated as infinite.
  startingGear: AssistantGear
  department:
  - Civilian
  icon: "Assistant"
  access:
  - Maintenance

- type: startingGear
  id: AssistantGear
  equipment:
    innerclothing: ClothingUniformJumpsuitColorGrey
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesBlack
    idcard: AssistantPDA
    ears: ClothingHeadsetService
