- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 # 5 hours
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hop
  canBeAntag: true
  access:
  - Brig
  - Maintenance
  - Service
  - Detective
  extendedAccess:
  - Security

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackFilledDetective
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilledNonlethal
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelFilledDetective
  duffelbag: ClothingBackpackDuffelFilledDetective
