- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  playTimeTracker: JobServiceWorker
  requirements:
    - !type:DepartmentTimeRequirement
      department: Service
      time: 1800
      inverted: true # stop playing intern if you're good at service!
  startingGear: ServiceWorkerGear
  icon: "ServiceWorker"
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
