- type: job
  id: ServiceWorker
  name: "service worker"
  startingGear: ServiceWorkerGear
  departments:
  - Civilian
  icon: "ServiceWorker"
  supervisors: "the bartender, chefs, botanists, and head of personnel"
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: AssistantPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
