- type: job
  id: Roboticist
  name: "roboticist"
  startingGear: RoboticistGear
  departments:
  - Science
  icon: "Scientist"
  supervisors: "the research director"
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    hands: ClothingHandsGlovesFingerless
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    ears: ClothingHeadsetRobotics
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
