- type: job
  id: Scientist
  name: "scientist"
  positions: 3
  spawnPositions: 2
  startingGear: ScientistGear
  department:
  - Science
  icon: "Scientist"
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  equipment:
    innerclothing: ClothingUniformJumpsuitScientist
    backpack: BackpackClothingFilled
    shoes: ClothingShoesWhite
    outerclothing: OuterclothingLabcoat
    idcard: SciencePDA
    ears: HeadsetScience
