- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20h overall
