- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10h

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # 30h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 10h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 144000 # 40
  - !type:DepartmentTimeRequirement
    department: Security
    time: 108000 # 30
  # should be changed to nukie playtime when thats tracked (wyci)
