- type: antag
  id: Nukeops
  name: antag-role-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: antag-role-nuclear-operative-objective

- type: antag
  id: NukeopsCommander
  name: antag-role-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: antag-role-nuclear-operative-commander-objective
