# TODO: Add descriptions (many)
# TODO BODY: Part damage
- type: entity
  id: BasePart
  parent: BaseItem
  name: "body part"
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological
  - type: BodyPart
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
      - Trash

- type: entity
  id: TorsoBase
  name: "torso"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Torso

- type: entity
  id: HeadBase
  name: "head"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Head
    vital: true
  - type: Input
    context: "ghost"
  - type: Tag
    tags:
      - Head

- type: entity
  id: LeftArmBase
  name: "left arm"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Left

- type: entity
  id: RightArmBase
  name: "right arm"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Right

- type: entity
  id: LeftHandBase
  name: "left hand"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Left

- type: entity
  id: RightHandBase
  name: "right hand"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Right

- type: entity
  id: LeftLegBase
  name: "left leg"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Left
  - type: MovementBodyPart

- type: entity
  id: RightLegBase
  name: "right leg"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Right
  - type: MovementBodyPart

- type: entity
  id: LeftFootBase
  name: "left foot"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Left

- type: entity
  id: RightFootBase
  name: "right foot"
  parent: BasePart
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Right
