- type: entity
  name: random detective corpse spawner #RANDOM DETECTIVE
  id: RandomSpawnDetectiveCorpse
  parent: MarkerBase
  components:
  - type: Sprite
    layers:
      - state: red
      - sprite: Markers/jobs.rsi
        state: detective
      - state: dead
  - type: RandomSpawner
    prototypes:
      - DetectiveFilledDefaultCorpse
      - DetectiveEmptyDefaultCorpse
      - DetectiveFilledCoatCorpse
      - DetectiveEmptyCoatCorpse
    chance: 1

- type: entity
  name: random security officer corpse spawner #RANDOM SECURITY OFFICER
  id: RandomSpawnSecurityOfficerCorpse
  parent: MarkerBase
  components:
  - type: Sprite
    layers:
      - state: red
      - sprite: Markers/jobs.rsi
        state: security_officer
      - state: dead
  - type: RandomSpawner
    prototypes:
      - SecurityOfficerFilledCorpse
      - SecurityOfficerEmptyCorpse
      - SecurityOfficerFilledBioCorpse
    chance: 1

- type: entity
  name: random warden corpse spawner #RANDOM WARDEN
  id: RandomSpawnWardenCorpse
  parent: MarkerBase
  components:
  - type: Sprite
    layers:
      - state: red
      - sprite: Markers/jobs.rsi
        state: warden
      - state: dead
  - type: RandomSpawner
    prototypes:
      - WardenFilledCorpse
      - WardenEmptyCorpse
    chance: 1

- type: entity
  name: random brig medic corpse spawner #RANDOM BRIG MEDIC
  id: RandomSpawnBrigMedicCorpse
  parent: MarkerBase
  components:
  - type: Sprite
    layers:
      - state: red
      - sprite: Markers/jobs.rsi
        state: brigmed
      - state: dead
  - type: RandomSpawner
    prototypes:
      - BrigmedicFilledCorpse
      - BrigmedicEmptyCorpse
    chance: 1

- type: entity
  name: random security corpse spawner #RANDOM SECURITY
  id: RandomSpawnSecurityCorpse
  parent: MarkerBase
  components:
  - type: Sprite
    layers:
      - state: red
      - sprite: Markers/jobs.rsi
        state: security_officer
      - state: dead
  - type: RandomSpawner
    prototypes:
      - DetectiveFilledDefaultCorpse
      - DetectiveEmptyDefaultCorpse
      - DetectiveFilledCoatCorpse
      - DetectiveEmptyCoatCorpse
      - SecurityOfficerFilledCorpse
      - SecurityOfficerEmptyCorpse
      - SecurityOfficerFilledBioCorpse
      - WardenFilledCorpse
      - WardenEmptyCorpse
      - BrigmedicFilledCorpse
      - BrigmedicEmptyCorpse
    chance: 1