- type: job
  id: LogisticsSpecialist
  name: job-name-logispec
  description: job-description-logispec
  playTimeTracker: JobLogisticsSpecialist
  startingGear: LogisticsSpecialistGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Logistics
  - Maintenance

- type: startingGear
  id: LogisticsSpecialistGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
