- type: job
  id: MysticQuartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobMysticQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobLogisticsSpecialist
      time: 21600 #6 hrs
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-director
  canBeAntag: false
  access:
  - Logistics
  - Quartermaster
  - Maintenance
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
