# HoS
- type: entity
  id: LockerHeadOfSecurity
  parent: LockerSecureBase
  name: "Head of Security's Locker"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer2D
      state: hos

  - type: Icon
    state: hos_door

# Warden
- type: entity
  id: LockerWarden
  parent: LockerSecureBase
  name: "Warden's Locker"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer2D
      state: warden

  - type: Icon
    state: warden_door

# Security Officer
- type: entity
  id: LockerSecurity
  parent: LockerSecureBase
  name: "Security Officer's Locker"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer2D
      state: sec

  - type: Icon
    state: sec_door

# LockerHeadOfSecurity Filled
- type: entity
  id: LockerHeadOfSecurityFilled
  suffix: Filled
  parent: LockerHeadOfSecurity

# LockerWarden Filled
- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden

# LockerSecurity Filled
- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
