- type: entity
  name: stun baton
  parent: BaseItem
  id: Stunbaton
  description: A stun baton for incapacitating people with. Actively harming with this is considered bad tone.
  components:
  - type: Sprite
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    netsync: false
    layers:
    - state: stunbaton_off
      map: [ "enum.ToggleVisuals.Layer" ]
  - type: Stunbaton
    energyPerUse: 100
  - type: MeleeWeapon
    damage:
      types:
        Blunt: 7
    bluntStaminaDamageFactor: 2.0
    angle: 60
    animation: WeaponArcSlash
  - type: StaminaDamageOnHit
    damage: 55
  - type: Battery
    maxCharge: 1000
    startingCharge: 1000
  - type: ItemCooldown
  - type: Item
    heldPrefix: off
    size: 20
  - type: Clothing
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    quickEquip: false
    slots:
    - Belt
  - type: DisarmMalus
    malus: 0.225
  - type: Appearance
  - type: GenericVisualizer
    visuals:
     enum.ToggleVisuals.Toggled:
        enum.ToggleVisuals.Layer:
          True: {state: stunbaton_on}
          False: {state: stunbaton_off}
  - type: StaticPrice
    price: 100

- type: entity
  name: flash
  parent: BaseItem
  id: Flash
  description: An ultrabright flashbulb with a trigger, which causes the victim to be dazed and lose their eyesight for a moment. Useless when burnt out.
  components:
    - type: Sprite
      sprite: Objects/Weapons/Melee/flash.rsi
      state: flash
    - type: Flash
    - type: MeleeWeapon
      damage:
        types:
          Blunt: 0 # why is this classed as a melee weapon? Is it needed for some interaction?
      angle: 10
    - type: Item
      size: 5
      sprite: Objects/Weapons/Melee/flash.rsi
    - type: ItemCooldown
    - type: StaticPrice
      price: 40