- type: randomHumanoidSettings
  id: RandomServiceCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
      - HoPGear
      - ClownGear
      - MimeGear
      - JanitorGear
      - ServiceWorkerGear
      - MusicianGear
      - BotanistGear
      - ChefGear
      - ChaplainGear
      - PassengerGear

- type: randomHumanoidSettings
  id: RandomCargoCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
    - CargoTechGear
    - SalvageSpecialistGear

- type: randomHumanoidSettings
  id: RandomEngineerCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
    - TechnicalAssistantGear
    - AtmosphericTechnicianGear
    - StationEngineerGear

- type: randomHumanoidSettings
  id: RandomMedicCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
    - MedicalInternGear
    - PsychologistGear
    - ChemistGear
    - DoctorGear

- type: randomHumanoidSettings
  id: RandomScienceCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
    - ResearchAssistantGear
    - ScientistGear

- type: randomHumanoidSettings
  id: RandomSecurityCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
    - SecurityCadetGear
    - SecurityOfficerGear
    - DetectiveGear
    - WardenGear

- type: randomHumanoidSettings
  id: RandomCommandCorpse
  randomizeName: false
  components:
  - type: Damageable
    damage:
      types:
        Bloodloss: 49
        Asphyxiation: 76
        Slash: 56
        Blunt: 19
  - type: Inventory
    templateId: corpse
  - type: Loadout
    prototypes:
    - HoPGear
    - CentcomGear
    - CaptainGear
    - HoSGear
    - ResearchDirectorGear
    - CMOGear
    - ChiefEngineerGear
    - QuartermasterGear
