name: Build & Publish Docfx

env:
  DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docfx:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Master
      uses: actions/checkout@v2

    - name: Setup submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: wrexbe/cache@mycache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-wrexbe4-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-wrexbe4-

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore /p:WarningsAsErrors=nullable

    - name: Build DocFX
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: Content.Docfx/docfx.json

    - name: Publish Docfx Documentation on GitHub Pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: Content.Docfx/_content-site
        GH_PAT: ${{ secrets.GH_PAT }}
