name: Check Merge Conflicts

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [synchronize]

jobs:
  Label:
    if: github.actor != 'PJBot'
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: eps1lon/actions-label-merge-conflict@v3.0.0
        with:
          dirtyLabel: "Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
