name: "Labels: UI"

on:
  pull_request:
    paths:
      - '**.xaml**'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Changes: UI"
