name: "Labels: Changes"

on:
  pull_request_review:
    types: [submitted]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Awaiting Changes"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Needs Review"

