name: "Labels: No C#"

on:
  pull_request:
    paths:
      - '!**.cs'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "No C#"
