name: Map Diff Comment

on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    paths:
    - 'Resources/Maps/**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        name: Check changed files
        uses: trilom/file-changes-action@v1.2.4
        with:
          fileOutput: 'yml'
          persist-credentials: false
          fetch-depth: 0
      - name: Set environment variables
        run: |
            echo "FILES_ADDED=${{ steps.file_changes.outputs.files_added }}" >> $GITHUB_ENV
            echo "FILES_MODIFIED=${{ steps.file_changes.outputs.files_modified }}" >> $GITHUB_ENV
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
      - name: Setup submodule
        run: |
          git submodule update --init --recursive
          touch BuildChecker/DISABLE_SUBMODULE_AUTOUPDATE
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: dotnet restore
      - name: Create map images
        run: dotnet run --project Content.MapRenderer/Content.MapRenderer.csproj --no-build --no-restore
      - name: Upload map images
        uses: devicons/public-upload-to-imgur@main
        id: new_map_images
        with:
          path: ./Resources/MapImages/
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: View results
        env:
          STEP_1_RESULT: ${{ steps.new_map_images.outputs.imgur_urls }}
        run: |
          echo $STEP_1_RESULT
