name: Update JSON files on wiki

on:
  push:
    branches: [ master, jsondump ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      - 'RobustToolbox/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup submodule
      run: |
        git submodule update --init --recursive
    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5
    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors=nullable /m
    - name: Generate JSON
      run: dotnet ./bin/Content.Server/Content.Server.dll --cvar autogen.destination_file=prototypes.json
      continue-on-error: true
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload chem_prototypes.json
      uses: jtmullen/mediawiki-edit-action@v0.1.1
      with:
        wiki_text_file: ./bin/Content.Server/data/chem_prototypes.json
        edit_summary: Update chem_prototypes.json via GitHub Actions
        page_name: "User:NexBot/chem_prototypes.json"
        api_url: https://wiki.spacestation14.io/w/api.php
        username: ${{ secrets.WIKI_BOT_USER }}
        password: ${{ secrets.WIKI_BOT_PASS }}

